app:
  timezone: America/New_York
  title: "S-STEM Preparatory Phase \u2014 Dashboard"
recipients:
- calliert@gram.edu
- rawalb@gram.edu
- daniellengrayphd@gmail.com
smtp:
  host: smtp.gmail.com
  password: aomn albw lybb uhni
  port: 465
  use_ssl: true
  username: YOUR_SMTP_USERNAME
